version: '3.8'

services:
  postgres:
    image: postgres:17.4
    restart: always
    container_name: rcci-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: rcci
    volumes:
      - rcci_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - rcci_network

  pgadmin:
    image: dpage/pgadmin4:9.2.0
    container_name: rcci-pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-admin@admin.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-pgadmin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres
    networks:
      - rcci_network

  # app:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: rcci-app
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/rcci?schema=public
  #     - AUTH_SECRET=${AUTH_SECRET}
  #     - NODE_ENV=production
  #   depends_on:
  #     postgres:
  #       condition: service_healthy
  #   networks:
  #     - rcci_network

volumes:
  rcci_postgres_data: 
  pgadmin_data:

networks:
  rcci_network:
    driver: bridge

